default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: documents_dev
  user: documents
  password: documents
  host: 127.0.0.1
  port: 6543

test:
  <<: *default
  database: documents_test
  user: documents
  password: documents
  host: 127.0.0.1
  port: 6543

production:
  <<: *default
